### ISSUE TITLE
windows 10 , install error

### ISSUE THREAD

**Issue by xjtu19** [aalavandhaann/chenhan_cython#2]
(py310) PS D:\chenhan_cython> pip install py_chenhancc
Collecting py_chenhancc
  Using cached py_chenhancc-0.0.7.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      C:\Users\26735\AppData\Local\Temp\pip-install-h_h4zq9z\py-chenhancc_dd7701e3e136468b9ca93684466a3bf7\setup.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import os, platform, pkg_resources
      Traceback (most recent call last):
        File "C:\Users\26735\anaconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 386, in get_provider
          module = sys.modules[moduleOrReq]
      KeyError: 'autowrap'
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\26735\AppData\Local\Temp\pip-install-h_h4zq9z\py-chenhancc_dd7701e3e136468b9ca93684466a3bf7\setup.py", line 15, in <module>
          data_dir = pkg_resources.resource_filename("autowrap", "data_files")
        File "C:\Users\26735\anaconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 1181, in resource_filename
          return get_provider(package_or_requirement).get_resource_filename(
        File "C:\Users\26735\anaconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 388, in get_provider
          __import__(moduleOrReq)
      ModuleNotFoundError: No module named 'autowrap'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(py310) PS D:\chenhan_cython>

**Comment by xjtu19** [comment]
Following the error tips, I installed the package **autowrap**, it's OK now.
Successfully installed py_chenhancc~~

(py310) PS D:\chenhan_cython> pip install autowrap
Collecting autowrap
  Downloading autowrap-0.22.11-py3-none-any.whl.metadata (916 bytes)
Requirement already satisfied: Cython>=0.19 in c:\users\26735\anaconda3\envs\py310\lib\site-packages (from autowrap) (3.0.10)
Requirement already satisfied: setuptools in c:\users\26735\anaconda3\envs\py310\lib\site-packages (from autowrap) (69.5.1)
Downloading autowrap-0.22.11-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.7 MB/s eta 0:00:00
Installing collected packages: autowrap
Successfully installed autowrap-0.22.11
(py310) PS D:\chenhan_cython> pip install py_chenhancc
Collecting py_chenhancc
  Using cached py_chenhancc-0.0.7.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: autowrap>=0.22 in c:\users\26735\anaconda3\envs\py310\lib\site-packages (from py_chenhancc) (0.22.11)
Requirement already satisfied: Cython>=0.19 in c:\users\26735\anaconda3\envs\py310\lib\site-packages (from autowrap>=0.22->py_chenhancc) (3.0.10)
Requirement already satisfied: setuptools in c:\users\26735\anaconda3\envs\py310\lib\site-packages (from autowrap>=0.22->py_chenhancc) (69.5.1)
Building wheels for collected packages: py_chenhancc
  Building wheel for py_chenhancc (setup.py) ... done
  Created wheel for py_chenhancc: filename=py_chenhancc-0.0.7-cp310-cp310-win_amd64.whl size=97769 sha256=3b1bcaaab2ebb736a9b82a8dd8c6d568c8bf65f1f0792846ca94a8823d16ea46
  Stored in directory: c:\users\26735\appdata\local\pip\cache\wheels\71\d3\c9\64079034dbe1b8fa759adec5c6fba1d52e305bbd948ff34631
Successfully built py_chenhancc
Installing collected packages: py_chenhancc
Successfully installed py_chenhancc-0.0.7
(py310) PS D:\chenhan_cython>
